### ISSUE TITLE
support for http

### ISSUE THREAD

**Issue by Kleak** [dart-lang/grpc-dart#38]
does the package support http ?

```proto
syntax = "proto3";
package example;

import "google/api/annotations.proto";

message StringMessage {
  string value = 1;
}
 
service YourService {
  rpc Echo(StringMessage) returns (StringMessage) {
    option (google.api.http) = {
      post: "/v1/example/echo"
      body: "*"
    };
  }
}
```

**Comment by jakobr-google** [comment]
This package supports the [gRPC protocol](https://grpc.io/), which is [based on HTTP/2](https://grpc.io/docs/guides/wire.html).

The `google.api.http` options are for an older JSON/REST-based RPC system. I'm not sure if there are Dart packages that support it directly, but [dart-lang/googleapis](https://github.com/dart-lang/googleapis) comes close (except that it's based on the API discovery documents rather than protobuf definition files).

**Comment by Kleak** [comment]
Can we use the client inside a browser ?

**Comment by jakobr-google** [comment]
Probably not as is, since package:http2 (which this package uses for the communication) is based on raw sockets.

There is a [proposal](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) for a HTTP-based encapsulation of the protocol for browsers, but it's still in development, and this package doesn't implement any of it yet.

**Comment by gedw99** [comment]
You can use GRPC in the browser.

https://github.com/johanbrandhorst/grpcweb-example/

Whats going on here ?
Basically the grpc proto is being code generated to use web sockets. There is a golang gateway thats converts between a web sockets and grpc call.

It also code generates the Client side code to golang and then transpiles it to JS.
There is no reason it cant also code gen to Dart !

**Comment by jakobr-google** [comment]
@gedw99 You should (maybe with a few modifications) be able to do something similar with the current code, if you supply your own implementation of the ClientChannel interface to the generated client stubs. I'd be happy to take a PR for this.

I don't see how that's relevant for Flutter, though, since Flutter doesn't involve a browser. This library specifically supports Flutter as is -- that's the main reason for it's existence. If you're having problems using this library with Flutter, then please file an issue.

**Comment by gedw99** [comment]
Thanks. Will see what I can conjure up

**Comment by jakobr-google** [comment]
Thanks! I've filed issue #43 to track this. We can have design discussions, if needed, over there.

**Comment by gedw99** [comment]
@MarcusLongmuir fyi.

Figured you will be interested in dart / flutter GUI's being able to use golang backend.
